### PR TITLE
Fixed the colon problem

### PR DESCRIPTION
**Pull request by siasur**
Replaced all ":" with "." for compatibility

### CODE REVIEW

**Comment by devryan** [comment]
Have you tested this on your systems with both local+remote mode?

**Comment by siasur** [comment]
It's untested right now. couldn't test it because my home server needs a fresh reinstall. Will test it tomorrow.

**Comment by devryan** [comment]
Awesome, thanks.

**Comment by devryan** [comment]
Note that any scripts in Remote that are updated need to go into the 'gpx-remote-latest.tar.gz' tarball as well as the bin directory.

**Comment by siasur** [comment]
couldn't finish my test yesterday, my internet connection was very slow and the setup of my test environment took ages.

Will test it today!

**Comment by devryan** [comment]
Cool.  Let me know, then I will test on my end.

**Comment by hacktrix2006** [comment]
I have been testing the colonfix for the remote and the servers will now start and stop as the user that server is assigned to without issues. However it does make the WebGUI's FTP tab not work however the colonfix works.

**Comment by devryan** [comment]
Ahh - yes.  These game server directory structures are hardcoded here:

https://github.com/devryan/GamePanelX-V3/blob/master/includes/classes/files.php#L149
https://github.com/devryan/GamePanelX-V3/blob/master/includes/classes/network.php#L300

So the master code will need to be updated.  On my local dev setup I've already addressed most of those issues so I will get that committed out.  

We ought to develop on a branch for all this stuff.  I think you have to pay for that on github, but I will look into it.

**Comment by hacktrix2006** [comment]
Nice one bud. I nice to see people helping one another out thats for sure.

**Comment by siasur** [comment]
whoops... thought i had commented here already. I couldn't test this fix on my testserver 'cause the mainboard is broken. (It's a very old desktop pc).

Sorry, that I'm late in answering.

@devryan You don't have to pay for branches... just for private repos.
@hacktrix2006 Thanks for your testing :)

**Comment by devryan** [comment]
@siasur, @hacktrix2006 I have created a dev branch on GPX Master and Remote repos.  Let's submit pull requests and dev/test there.

https://github.com/devryan/GamePanelX-V3/tree/dev
https://github.com/devryan/GamePanelX-V3-Remote/tree/dev

**Comment by devryan** [comment]
Can you guys submit your pull requests to the dev branch?  I can't seem to move them.

**Comment by hacktrix2006** [comment]
My commit was already put into the remote's master as it was the #!/bin/bash bit so only the commit from siasur is needed

**Comment by devryan** [comment]
Cool.  I am usually in #gamepanelx on irc.freenode.net fyi.

**Comment by hacktrix2006** [comment]
Roger that have to fix router first like though LOL using mobile atm.

**Comment by siasur** [comment]
will move it...
I'm currently a little bit busy, so sorry for my late answers every time.

**Pull request merged**
