### PR TITLE
Changed the colon in the path to fix a srcds_run related bug

### PR DESCRIPTION
**Pull request by siasur**
I continued the "fix" from ExGamers. It's completed now.

### CODE REVIEW

**Comment by devryan** [comment]
Wow.  Thanks for the updates.  I had this about half-way done, though I had used a "." (like netstat does) instead of a - or a _.  I'd say we should make it a dot instead of hyphen, in case any other games hate those characters.

**Comment by devryan** [comment]
Also, why are you changing the ip:port to service$tplid?  If $tplid is the template ID, then you effectively couldn't have multiple servers of the same template under a user account.  This simply needs to be fixed to $ip.$port, just like netstat shows ip/port combinations.

**Comment by siasur** [comment]
> Also, why are you changing the ip:port to service$tplid?

I was not the one who made this change.  @ExGamers did it initially, but then changed it to `$ip-$port`. But he changed it in just one file. That's why I took his "fix" and completed it.

Give me some time and I'll create a new Pullrequest with a "." instead of a "-"

**Comment by devryan** [comment]
Ok awesome.  Thanks!

**Comment by siasur** [comment]
You can close this now :)

**Pull request closed without merging**
