### PR TITLE
fixed update always running steam even for non steam games

### PR DESCRIPTION
**Pull request by fritz-net**
fix for issue: https://github.com/devryan/GamePanelX-V3/issues/131

### CODE REVIEW

**Comment by fritz-net** [comment]
untested for steam game cause I don't one any

**Comment by fritz-net** [comment]
patch was not working, corrected:
https://github.com/fritz-net/GamePanelX-V3-Remote/commit/128f940a78e1436e5f10ee1bd88c7e061ec4be49

**Comment by devryan** [comment]
Thanks!  Sorry for the delayed merge :)

**Comment by fritz-net** [comment]
haha no problem ;) I'm happy anyway about my first accepted merge :)

**Pull request merged**
